# Generated by Django 3.2.16 on 2023-03-19 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=1000)),
                ('game_file_link', models.CharField(max_length=1000)),
                ('file_location', models.CharField(max_length=1000)),
                ('game_year', models.IntegerField()),
                ('cover', models.CharField(max_length=1000)),
                ('file_size', models.FloatField()),
                ('rma_file', models.FileField(blank=True, upload_to='rmaFolder/')),
                ('rbf_file', models.FileField(blank=True, upload_to='rbfFolder/')),
                ('game_type', models.CharField(max_length=1000)),
                ('manufacturer', models.CharField(max_length=1000)),
                ('category', models.CharField(max_length=1000)),
            ],
        ),
    ]
